# Generated by Django 6.0.6 on 2026-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usia', models.FloatField()),
                ('bmi', models.FloatField()),
                ('usia_kehamilan', models.FloatField()),
                ('sistolik', models.FloatField()),
                ('diastolik', models.FloatField()),
                ('proteinuria', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertensi', models.BooleanField(default=False)),
                ('gejala_aktif', models.CharField(blank=True, max_length=200)),
                ('rule_aktif', models.CharField(blank=True, max_length=500)),
                ('rule_result', models.CharField(blank=True, max_length=10)),
                ('ml_result', models.CharField(blank=True, max_length=10)),
                ('final_result', models.CharField(choices=[('low', 'LOW RISK'), ('mid', 'MID RISK'), ('high', 'HIGH RISK')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_rule', models.CharField(max_length=10, unique=True)),
                ('kondisi', models.CharField(max_length=255)),
                ('risiko', models.CharField(max_length=10)),
                ('confidence', models.FloatField(default=1.0)),
                ('support', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['kode_rule'],
            },
        ),
    ]
